name: Tests

on:
  push:
  pull_request:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          npm ci
      - name: Run Tests
        run: |
          npm test

  django-sqlite:
    name: py-${{ matrix.python }} dj-${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Django supported on latest - dj4.2, py3.11
          - python: 3.11
            django: 4.2
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "django~=${{ matrix.django }}.0"
      - name: Test
        run: |
          pytest
