name: Tests

on:
  push:
  pull_request:

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm ci
      - name: Run Tests
        run: |
          npm test